/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ClientAreaRouteImport } from './routes/client-area'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InquireRouteImport } from './routes/inquire'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAreaRoute = ClientAreaRouteImport.update({
  id: '/client-area',
  path: '/client-area',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InquireRoute = InquireRouteImport.update({
  id: '/inquire',
  path: '/inquire',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-area': typeof ClientAreaRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/inquire': typeof InquireRoute
  '/locations': typeof LocationsRoute
  '/portfolio': typeof PortfolioRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sessions': typeof SessionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-area': typeof ClientAreaRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/inquire': typeof InquireRoute
  '/locations': typeof LocationsRoute
  '/portfolio': typeof PortfolioRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sessions': typeof SessionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-area': typeof ClientAreaRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/inquire': typeof InquireRoute
  '/locations': typeof LocationsRoute
  '/portfolio': typeof PortfolioRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sessions': typeof SessionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/client-area'
    | '/experiences'
    | '/faq'
    | '/inquire'
    | '/locations'
    | '/portfolio'
    | '/robots.txt'
    | '/sessions'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/client-area'
    | '/experiences'
    | '/faq'
    | '/inquire'
    | '/locations'
    | '/portfolio'
    | '/robots.txt'
    | '/sessions'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/client-area'
    | '/experiences'
    | '/faq'
    | '/inquire'
    | '/locations'
    | '/portfolio'
    | '/robots.txt'
    | '/sessions'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClientAreaRoute: typeof ClientAreaRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FaqRoute: typeof FaqRoute
  InquireRoute: typeof InquireRoute
  LocationsRoute: typeof LocationsRoute
  PortfolioRoute: typeof PortfolioRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SessionsRoute: typeof SessionsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-area': {
      id: '/client-area'
      path: '/client-area'
      fullPath: '/client-area'
      preLoaderRoute: typeof ClientAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquire': {
      id: '/inquire'
      path: '/inquire'
      fullPath: '/inquire'
      preLoaderRoute: typeof InquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClientAreaRoute: ClientAreaRoute,
  ExperiencesRoute: ExperiencesRoute,
  FaqRoute: FaqRoute,
  InquireRoute: InquireRoute,
  LocationsRoute: LocationsRoute,
  PortfolioRoute: PortfolioRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SessionsRoute: SessionsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
